services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify-nest
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: nestuser
      DATABASE_PASSWORD: root
      DATABASE_NAME: nestdb

  mysql:
    image: mysql:8.0
    container_name: nest_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestdb
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
